presentation/Store.Web/Models/Cart.cs
namespace Store.Web.Models
{
    public class Cart
    {
        public IDictionary<int, int> Items { get; set; } = new Dictionary<int, int>();

        public decimal Amount { get; set; }
    }
}

presentation/Store.Web/Models/ErrorViewModel.cs
namespace Store.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

presentation/Store.Web/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;

namespace Store.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;

        public BookController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        public IActionResult Index(int id)
        {
            Book book = _bookRepository.GetById(id);

            return View(book);
        }
    }
}

presentation/Store.Web/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.Models;

namespace Store.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly IBookRepository _bookRepository;

        public CartController(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        public IActionResult Add(int id)
        {
            var book = _bookRepository.GetById(id);
            Cart cart;

            if (!HttpContext.Session.TryGetCart(out cart))
                cart = new Cart();

            if (cart.Items.ContainsKey(id)) 
            {
                cart.Items[id]++;
            }
            else
            {
                cart.Items[id] = 1;
            }

            cart.Amount += book.Price;

            HttpContext.Session.Set(cart);

            return RedirectToAction("Index", "Book", new { id });
        }
    }
}

presentation/Store.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Web.Models;
using System.Diagnostics;

namespace Store.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

presentation/Store.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;

namespace Store.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly BookService _bookService;

        public SearchController(BookService bookService)
        {
            _bookService = bookService;
        }

        public IActionResult Index(string query) 
        {
            var books = _bookService.GetAllByQuery(query);

            return View(books);
        }
    }
}

presentation/Store.Web/Views/Book/Index.cshtml
@using Store
@model Book

@{
    ViewData["Title"] = Model.Title;
}

<h1>@Model.Title</h1>
<p><strong>@Model.Autor</strong></p>
<p>@Model.Description</p>
<p>Цена: <strong>@Model.Price</strong> руб.</p>
<form action="@Url.Action("Add", "Cart")" method="post">
    <input type="hidden" name="id" value="@Model.Id"/>
    <button class="btn btn-outline-success" type="submit">В корзину</button>
</form>

presentation/Store.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Добро пожаловать!";
}

<h1>Развлекайтесь! :)</h1>
<h2 >Предупреждение! Все книги и их авторы вымышлены! Все совпадения случайны и разработчик не имеет цели оскорбить чью-то честь и достоинство!</h2>

presentation/Store.Web/Views/Search/Index.cshtml
@model Store.Book[]

@{
    ViewData["Title"] = "Результаты поиска";
}

<h1>Результаты поиска</h1>

@if(Model.Length == 0)
{
    <p>Ничего не найдено.</p>
}
else
{
    <ul>
        @foreach (var book in Model)
        {
            <li><a href="@Url.Action("Index", "Book", new { id = book.Id })">@book.Title</a></li>
        }
    </ul>
}

presentation/Store.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Крутые книги тут</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Store.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Крутые книги тут</a>
            <form class="form-inline my-2 my-lg-0" action="@Url.Action("Index", "Search")" method="get">
                <input class="form-control mr-sm-2" type="search" name="query" placeholder="Автор или название"/>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
            </form>
            <span class="navbar-text ml-auto">
                @{
                    Cart cart;

                    if (!Context.Session.TryGetCart(out cart))
                        cart = new Cart();

                    if (cart.Items.Count == 0)
                    {
                        @:Корзина пуста
                    }
                    else
                    {
                        @:Товаров @cart.Items.Count на сумму @cart.Amount
                    }
                }
            </span>
        </nav>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>